steps:
  - name: node
    dir: "functions"
    entrypoint: npm
    args: ["install"]
  - name: gcr.io/$PROJECT_ID/firebase
    dir: "functions"
    args: ["deploy", "--project=$PROJECT_ID", "--only=functions"]
