steps:
  - name: node
    dir: "functions"
    entrypoint: npm
    args: ["install"]
  - name: gcr.io/$PROJECT_ID/firebase
    entrypoint: 'bash'
    args:
      - '-c'
      - 'if [[ "$_PR_NUMBER" = "" ]]; then firebase deploy --project=$PROJECT_ID --only=functions; fi'
