steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://the-quest-config/firebase.config.ts", "./firebase.config.ts"]
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["run", "build"]
  - name: gcr.io/$PROJECT_ID/firebase
    args: ["deploy", "--project=$PROJECT_ID", "--only=hosting"]
